ASN.1: Clean up include statements in public headers
[ Upstream commit 4df86c6ea5c37fe0452638f39a1e4b189da75c54 ]

If <linux/asn1_decoder.h> is the first header included from a .c file
(due to headers being sorted alphabetically), the compiler complains:

  include/linux/asn1_decoder.h:18:29: error: unknown type name 'size_t'

Avoid by including <linux/types.h>.

Jonathan notes that the counterpart <linux/asn1_encoder.h> already
includes <linux/types.h>, but additionally includes the unnecessary
<linux/bug.h>.  Drop it.

Signed-off-by: Lukas Wunner <lukas@wunner.de>
Reviewed-by: Stefan Berger <stefanb@linux.ibm.com>
Reviewed-by: Jonathan Cameron <Jonathan.Cameron@huawei.com>
Signed-off-by: Herbert Xu <herbert@gondor.apana.org.au>
Stable-dep-of: fb3e566cafc3 ("minix: avoid overflow in bitmap block count calculation")
Signed-off-by: Sasha Levin <sashal@kernel.org>
Signed-off-by: Abdur Rahman <abdur.rahman@canonical.com>